### PR TITLE
Dev/view src

### PR DESCRIPTION
**Pull request by barrettk**
### High level changes
 - renamed function `view_src()` --> `v()`
 - better column widths and font sizes
 - alternate in shading each time a new `.subject_cols` occurs
 - `.subject_cols` and `.freeze_cols` can be vectors of multiple columns
 - improved header formatting with labels, adds class attribute
 - infer `.subject_cols` if not specified --> will look for "ID" and "USUBJID"
 - fixed/frozen columns, which defaults to include `.subject_cols`
 - other formatting improvements
 - shiny app bug fixes and improvements with handling subject columns

### Example
```r
path <- system.file("example-sdtm", package = "mrgda")
src_list <- read_src_dir(.path = path) %>% suppressMessages()

v(
  src_list$lb %>% dplyr::mutate(ID = as.numeric(factor(USUBJID))),
  .freeze_cols = "LBDTC" # Total columns froze would be ID, USUBJID, and LBDTC
)
```
image

### CODE REVIEW

**Comment by barrettk** [comment]
@andersone1 FYI let me know if this is an issue:
 - currently the shiny app will not filter all tables if the subject does not exist in that dataset. If it doesnt exist in that dataset, it will just not update beyond its last rendering. I tested this using two datasets with different USUBJID's. This could mainly be a concern if some datasets dont have all the same subjects (such as demographics and dosing).
 - The issue arises when passing a dataframe with no rows into `v()`, which just returns a blank `DT` datatable. Unclear why this doesnt happen within the app
 - The workaround I thought of doing, was creating a new table with one row that just says "no patients found" or something
 - Given that we have more future updates planned, and no one currently uses this function, I wasn't sure if this was a blocker.

Let me know what you think

**Comment by andersone1** [comment]
Notes (in progress)

- What happens to grey shading when data is not sorted by subject
- Probably do not need `group_id` anymore
- Subject col will only ever be one (for simplicity)

**Review by andersone1 — APPROVED** [review]

**Comment by andersone1** [comment]
> @andersone1 FYI let me know if this is an issue:
> 
> * currently the shiny app will not filter all tables if the subject does not exist in that dataset. If it doesnt exist in that dataset, it will just not update beyond its last rendering. I tested this using two datasets with different USUBJID's. This could mainly be a concern if some datasets dont have all the same subjects (such as demographics and dosing).
> * The issue arises when passing a dataframe with no rows into `v()`, which just returns a blank `DT` datatable. Unclear why this doesnt happen within the app
> * The workaround I thought of doing, was creating a new table with one row that just says "no patients found" or something
> * Given that we have more future updates planned, and no one currently uses this function, I wasn't sure if this was a blocker.
> 
> ### Example
> #### Dataset 1:
> image
> 
> #### Dataset 2:
> image
> 
> Let me know what you think

@barrettk Code review is complete, everything looks good I am about to merge in. This issue with the shiny app / subject filtering isn't a blocker - we can decide how we want to handle this situation in subsequent releases.

**Comment by barrettk** [comment]
> @barrettk Code review is complete, everything looks good I am about to merge in. This issue with the shiny app / subject filtering isn't a blocker - we can decide how we want to handle this situation in subsequent releases.

I actually fixed this within this PR, so we should be good!

**Comment by andersone1** [comment]
Oh great 👍

**Pull request merged**
